name: Deploy curriculum site

on:
  push:
    branches:
      - main
    paths:
      - 'curriculum/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: cache gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gems-

      - name: install dependencies
        run: |
          gem install bundler
          bundle config set path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: build jekyll site (source=./curriculum) <------
        run: |
          bundle exec jekyll build --source ./curriculum --destination ./_site

      - name: configure pages
        uses: actions/configure-pages@v3

      - name: upload artifact (site)
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site

      - name: deploy to gitHub pages
        uses: actions/deploy-pages@v1
